// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Generated by tools/abi_reference/gen_reference_mach_traps.py (workspace).
// Sources: abi-reference/<tag>/mach_traps.json, firmware/<build>.json.
// CONFIG_EMBEDDED=true, ARM32; public desktop evidence cannot override
// audited iOS contracts. Firmware stubs attest presence, not full behavior.
#pragma once
#include <array>
#include <cstdint>
#include <string_view>
namespace ilemu::xnu_reference {
enum class MachSlot { UnknownProfile, Call, FirmwareStub, Invalid, Absent };
struct MachTable {
    std::string_view profile;
    std::string_view source;
    std::array<std::uint64_t, 2> calls;
    std::array<std::uint64_t, 2> firmware;
};
inline constexpr std::array mach_tables {
    MachTable { "darwin9.0.0d1",
        "xnu-792.24.17/osfmk/kern/syscall_sw.c",
        { 0x783b6affbc000000ULL, 0x00000010fe000000ULL }, { 0x783b7affbc000008ULL, 0x00000000fe000000ULL } },
    MachTable { "darwin9.3.1",
        "xnu-1228.15.4/osfmk/kern/syscall_sw.c",
        { 0x783b7affbc000000ULL, 0x000000107e000000ULL }, { 0x783b7affbc000008ULL, 0x000000007e000000ULL } },
    MachTable { "darwin9.4.1",
        "xnu-1228.15.4/osfmk/kern/syscall_sw.c",
        { 0x783b7affbc000000ULL, 0x000000107e000000ULL }, { 0x783b7affbc000008ULL, 0x000000007e000000ULL } },
    MachTable { "darwin10.0.0d3",
        "xnu-1456.1.26/osfmk/kern/syscall_sw.c",
        { 0x7c3b78ffbc000000ULL, 0x000000107e000000ULL }, { 0x783b7affbc000008ULL, 0x000000007e000000ULL } },
    MachTable { "darwin10.3.1-bootstrap-notify",
        "xnu-1504.3.12/osfmk/kern/syscall_sw.c",
        { 0x7c3b78ffbc000000ULL, 0x000000107e000000ULL }, { 0x0000000000000000ULL, 0x0000000000000000ULL } },
    MachTable { "darwin10.3.1-native-notify",
        "xnu-1504.3.12/osfmk/kern/syscall_sw.c",
        { 0x7c3b78ffbc000000ULL, 0x000000107e000000ULL }, { 0x0000000000000000ULL, 0x0000000000000000ULL } },
    MachTable { "darwin10.4.0",
        "xnu-1504.3.12/osfmk/kern/syscall_sw.c",
        { 0x7c3b78ffbc000000ULL, 0x000000107e000000ULL }, { 0x0000000000000000ULL, 0x0000000000000000ULL } },
    MachTable { "darwin11.0.0-inline-iokit",
        "xnu-1699.22.73/osfmk/kern/syscall_sw.c",
        { 0x7c3b70ffbc000000ULL, 0x000000107e000000ULL }, { 0x0000000000000000ULL, 0x0000000000000000ULL } },
    MachTable { "darwin11.0.0-wide-vm",
        "xnu-1699.22.73/osfmk/kern/syscall_sw.c",
        { 0x7c3b70ffbc000000ULL, 0x000000107e000000ULL }, { 0x0000000000000000ULL, 0x0000000000000000ULL } },
    MachTable { "darwin11.0.0-wide-vm-high-vectors",
        "xnu-1699.22.73/osfmk/kern/syscall_sw.c",
        { 0x7c3b70ffbc000000ULL, 0x000000107e000000ULL }, { 0x783b70ffbcfffc08ULL, 0x000000007e000000ULL } },
    MachTable { "darwin13.0.0-wide-vm-high-commpage",
        "xnu-2050.48.11/osfmk/kern/syscall_sw.c",
        { 0x7c3b70ffbcff5400ULL, 0x000000107e000000ULL }, { 0x783b70ffbcff5408ULL, 0x000000007e000000ULL } },
    MachTable { "darwin14.0.0",
        "xnu-2422.115.4/osfmk/kern/syscall_sw.c",
        { 0x7c3b7effbfffd400ULL, 0x000000107e000000ULL }, { 0x783b76ffbfffd408ULL, 0x000000007e000000ULL } },
    MachTable { "darwin14.0.0-fine-priority",
        "xnu-2782.40.9/osfmk/kern/syscall_sw.c",
        { 0x7c3b76ffbfffd400ULL, 0x000000107e000000ULL }, { 0x783b76ffbfffd408ULL, 0x000000007e000000ULL } },
    MachTable { "darwin15.0.0-qos-events",
        "xnu-3248.60.10/osfmk/kern/syscall_sw.c",
        { 0x7c3b76ffbfffd400ULL, 0x000000107e000000ULL }, { 0x783b76ffbfffd408ULL, 0x000000007e000000ULL } },
};
constexpr const MachTable* mach_table(std::string_view profile)
{
    for (const auto& table : mach_tables)
        if (table.profile == profile) return &table;
    return nullptr;
}
constexpr MachSlot mach_slot(const MachTable* table, std::uint32_t number)
{
    if (number >= 128U) return MachSlot::Absent;
    if (!table) return MachSlot::UnknownProfile;
    const auto bit = std::uint64_t { 1 } << (number % 64U);
    if (table->calls[number / 64U] & bit) return MachSlot::Call;
    if (table->firmware[number / 64U] & bit) return MachSlot::FirmwareStub;
    return MachSlot::Invalid;
}
} // namespace ilemu::xnu_reference
