add_subdirectory(device)
add_subdirectory(debug)
add_subdirectory(sysctl)
add_subdirectory(signal)
add_subdirectory(filesystem)
add_subdirectory(network)
add_subdirectory(process)
add_subdirectory(security)
add_subdirectory(vm)

target_sources(ilemu_kernel PRIVATE
    dispatch.cpp
    platform.cpp
    pthread_runtime.cpp
    psynch_runtime.cpp
    psynch.cpp
    aio.cpp
    audit_session.cpp
    fileport.cpp
    process.cpp
    posix_semaphore.cpp
    filesystem.cpp
    descriptor_lifecycle.cpp
    descriptor_memory.cpp
    bpf.cpp
    socket.cpp
    events.cpp
    device/offline_serial.cpp
    support.cpp)
target_link_libraries(ilemu_kernel PRIVATE
    iLEmu::kernel_bsd_baseband_device
    iLEmu::kernel_bsd_control
    iLEmu::kernel_bsd_debug
    iLEmu::kernel_bsd_filesystem_control
    iLEmu::kernel_bsd_filesystem_persistence
    iLEmu::kernel_bsd_filesystem_timestamps
    iLEmu::kernel_bsd_filesystem_locking
    iLEmu::kernel_bsd_filesystem_ownership
    iLEmu::kernel_bsd_virtual_udp_syscalls
    iLEmu::kernel_bsd_virtual_udp
    iLEmu::kernel_bsd_process
    iLEmu::kernel_bsd_security
    iLEmu::kernel_bsd_vm_shared_region
    iLEmu::kernel_bsd_signal
    iLEmu::kernel_bsd_sysctl)
